version: '3'

services:
  livraria_database:
    image: mysql:8.0
    restart: always
    expose:
      - 3306
    env_file:
      - livraria_database.env
      
  livraria_app:
    image: rodrigodevrj/livraria-api:1.0
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - livraria_database
    env_file:
      - livraria_app.env
      
